default_install_hook_types:
-   pre-commit
-   commit-msg
default_stages:
-   pre-commit
-   commit-msg
repos:
-   hooks:
    -   args: []
        id: conventional-pre-commit
        stages:
        -   commit-msg
    repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
